# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14d25b5fc779afbdbaaa720041f9eaa19b7e762b00ec5ab396a37ff9db15491e512a7fc524697cf9499c17fa660cfef17a29524435a773f75dbd121b2841a92e

test:
  secret_key_base: 1ee035a77a1902f93f94251fc62a71163519144bb86f829679aa4795c96c105ee88e9228dcfc877c76b97d17af1136feb7adb049e062227d123870359359dc22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
